set dotenv-load := true

# Default: list tasks
default:
    @just --list

# Bring up Postgres + Langfuse
up:
    docker compose up -d
    docker compose ps

# Stop services
down:
    docker compose down

# Run the API locally with reload
dev:
    cd backend && uv run uvicorn app.main:app --reload --port 8000

# Apply DB migrations
migrate:
    cd backend && uv run alembic upgrade head

# Create a new migration revision (autogenerated from models)
migration name:
    cd backend && uv run alembic revision --autogenerate -m "{{name}}"

# Unit tests (no external services)
test:
    cd backend && uv run pytest tests/ -v -m "not smoke"

# Smoke tests (hits Azure OpenAI; requires real .env)
smoke:
    cd backend && uv run pytest tests/ -v -m smoke

# Lint
lint:
    uv run ruff check backend/app backend/tests scripts
    uv run ruff format --check backend/app backend/tests scripts

# Auto-fix lint
fmt:
    uv run ruff check --fix backend/app backend/tests scripts
    uv run ruff format backend/app backend/tests scripts

# Type-check
typecheck:
    cd backend && uv run mypy app

# Generate synthetic claims (template mode)
synth:
    uv run python scripts/generate_synthetic_claims.py --out data/synthetic/claims.jsonl --seed 42

# Generate synthetic claims (LLM mode; costs ~$0.05)
synth-llm:
    uv run python scripts/generate_synthetic_claims.py --out data/synthetic/claims.jsonl --seed 42 --llm

# Extraction-only eval (Week 2)
eval-extraction:
    uv run --project backend python scripts/eval_extraction.py \
      --report-json data/synthetic/eval_extraction_report.json

# Decision pipeline eval (Week 3)
eval-decision:
    uv run --project backend python scripts/eval_decision.py \
      --report-json data/synthetic/eval_decision_report.json

# Full Week-4 eval — writes a Markdown report card and JSON to backend/app/evals/reports/
eval:
    uv run --project backend python scripts/run_eval.py

# Ingest the markdown corpus into pgvector with all 4 chunkers
ingest:
    uv run --project backend python scripts/ingest_corpus.py

# Ingest with contextual retrieval enabled (one extra LLM call/chunk)
ingest-ctx:
    uv run --project backend python scripts/ingest_corpus.py --with-context

# Bench the 4 chunkers on the 30-query retrieval eval (Week 5)
eval-retrieval:
    uv run --project backend python scripts/eval_retrieval.py

# Eval against a saved baseline; non-zero exit on >2pp regression
eval-regression:
    uv run --project backend python scripts/run_eval.py \
      --baseline backend/app/evals/reports/baseline.json

# Save the current eval result as the new baseline (use sparingly, intentionally)
eval-baseline:
    uv run --project backend python scripts/run_eval.py \
      --save-as-baseline backend/app/evals/reports/baseline.json

# One-command setup: docker up + migrate + sync deps. Assumes .env exists.
setup:
    docker compose up -d
    cd backend && uv sync
    cd backend && uv run alembic upgrade head
    @echo "ready: try 'just dev' or 'just demo'"

# 200-claim Phase-4 final eval — current production baseline
phase4-eval:
    uv run --project backend python scripts/run_eval.py \
      --claims data/synthetic/claims_phase3.jsonl \
      --no-faithfulness --judge-email-rate 0 \
      --baseline backend/app/evals/reports/phase4_baseline.json

# Lock the Phase-4 baseline (use only after confirming a clean run)
phase4-baseline:
    uv run --project backend python scripts/run_eval.py \
      --claims data/synthetic/claims_phase3.jsonl \
      --no-faithfulness --judge-email-rate 0 \
      --save-as-baseline backend/app/evals/reports/phase4_baseline.json

# Legacy Phase-3 baseline (preserved for reference / regression comparison)
phase3-eval:
    uv run --project backend python scripts/run_eval.py \
      --claims data/synthetic/claims_phase3.jsonl \
      --no-faithfulness --judge-email-rate 0 \
      --baseline backend/app/evals/reports/phase3_baseline.json

# Self-consistency audit — 40 claims × 3 runs at T=0.3 (~$0.12)
audit-consistency:
    uv run --project backend python scripts/self_consistency_audit.py

# Threshold sweep against the current baseline — Pareto curve of auto-rate vs accuracy
sweep:
    uv run --project backend python scripts/threshold_sweep.py \
      --eval backend/app/evals/reports/phase4_baseline.json \
      --out backend/app/evals/reports/threshold_sweep_phase4.md

# Run the prompt-injection pen test (9 adversarial inputs against the live pipeline)
pen-test:
    uv run --project backend python scripts/pen_test_injection.py

# Demo: live curl flow against a running API
demo:
    @echo "=== healthz ==="
    @curl -sf http://localhost:8000/healthz | jq .
    @echo "\n=== POST /api/claims/process (clear-approve battery defect) ==="
    @curl -sf -X POST http://localhost:8000/api/claims/process \
      -H 'Content-Type: application/json' \
      -d '{"raw_input":"My LevelUp 3 battery stopped charging after 3 months. SKU EB-LEVEL-3, only 25 charge cycles. Photos attached showing the battery and serial.","photo_descriptions":[]}' \
      | jq '{decision: .decision, route, calibrated_prob, queue_id, cost_breakdown: {ms: .latency_ms, prompt_versions}}'

# Drain pending Shopify webhook events into customers/orders
shopify-mirror:
    uv run --project backend python scripts/run_shopify_mirror.py --no-fixture

# Train the confidence calibrator from the latest eval JSONs
train-calibrator:
    uv run --project backend python scripts/train_calibrator.py
