"""Build the Consumer-Electronics Coverage Atlas from real plan T&Cs.

Loads each plan's key-terms doc (assembled from public sources under
`data/policies/ce_atlas_raw/`), runs the normalization engine to produce a
grounded `CoverageProfile`, verifies every cited clause is verbatim in the
source, and emits a cross-plan comparison + a grounding-integrity report.

This makes `docs/ce_atlas/coverage_atlas.md` reproducible: the hand-written
narrative there is the polished version; this regenerates the underlying
normalized data from the real terms.

Usage (needs an LLM key — OPENAI_API_KEY, optionally OPENAI_REASONER_MODEL):
    uv run --project backend python scripts/build_ce_atlas.py
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))

from app.atlas.extract import (  # noqa: E402
    extract_coverage_profile,
    verify_profile_grounding,
)
from app.atlas.schema import CoverageProfile  # noqa: E402

RAW_DIR = ROOT / "data" / "policies" / "ce_atlas_raw"
OUT = ROOT / "docs" / "ce_atlas" / "coverage_atlas_generated.md"

# (plan_name, source_url, filename)
PLANS = [
    (
        "AppleCare+ for iPhone",
        "https://www.apple.com/legal/sales-support/applecare/applecareplus/docs/applecareplusnaen.html",
        "applecare_plus.md",
    ),
    (
        "Samsung Care+",
        "https://www.samsung.com/us/support/samsung-care-plus/service-contract-terms-and-conditions/",
        "samsung_care_plus.md",
    ),
    (
        "Allstate Protection Plan",
        "https://www.squaretrade.com/coverage/",
        "allstate_protection.md",
    ),
]

_STATUS_GLYPH = {"covered": "✅", "conditional": "🟠", "excluded": "❌", "not_addressed": "—"}


def _cell(item) -> str:  # noqa: ANN001
    glyph = _STATUS_GLYPH.get(item.status, "?")
    detail = f" {item.detail}" if item.detail else ""
    return f"{glyph}{detail}".strip()


def _render(profiles: list[CoverageProfile], grounding: dict[str, tuple[int, int]]) -> str:
    names = [p.plan_name for p in profiles]
    lines: list[str] = []
    lines.append("# Coverage Atlas — generated")
    lines.append("")
    lines.append("Auto-generated by `scripts/build_ce_atlas.py` from the real plan terms in")
    lines.append("`data/policies/ce_atlas_raw/`. ✅ covered · 🟠 conditional · ❌ excluded · — not addressed.")
    lines.append("")
    lines.append("## Grounding integrity (cited clause verified verbatim in source)")
    lines.append("")
    lines.append("| Plan | Grounded cells |")
    lines.append("|---|---|")
    for p in profiles:
        g, t = grounding[p.plan_name]
        pct = (g / t * 100) if t else 0.0
        lines.append(f"| {p.plan_name} | {g}/{t} ({pct:.0f}%) |")
    lines.append("")
    lines.append("## Perils")
    lines.append("")
    lines.append("| Peril | " + " | ".join(names) + " |")
    lines.append("|---|" + "|".join(["---"] * len(names)) + "|")
    peril_maps = [p.peril_items() for p in profiles]
    for peril in peril_maps[0].keys():
        row = [peril.replace("_", " ")]
        row += [_cell(pm[peril]) for pm in peril_maps]
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")
    lines.append("## Terms")
    lines.append("")
    lines.append("| Term | " + " | ".join(names) + " |")
    lines.append("|---|" + "|".join(["---"] * len(names)) + "|")
    for term in ("term_length", "deductible_or_fee", "claim_limit", "transferable"):
        row = [term.replace("_", " ")]
        row += [_cell(getattr(p, term)) for p in profiles]
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")
    return "\n".join(lines) + "\n"


async def main() -> int:
    profiles: list[CoverageProfile] = []
    grounding: dict[str, tuple[int, int]] = {}

    async def one(plan_name: str, source: str, fname: str) -> CoverageProfile:
        text = (RAW_DIR / fname).read_text(encoding="utf-8")
        profile = await extract_coverage_profile(plan_name, source, text)
        g, t, ungrounded = verify_profile_grounding(profile, text)
        grounding[plan_name] = (g, t)
        print(f"[atlas] {plan_name}: grounded {g}/{t} cells" + (f"; ungrounded: {ungrounded}" if ungrounded else ""))
        return profile

    results = await asyncio.gather(*(one(*p) for p in PLANS))
    profiles.extend(results)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(_render(profiles, grounding))
    print(f"[atlas] wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
